global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'phishing-detection-monitor'

scrape_configs:
  - job_name: 'fastapi-app'
    scheme: https
    static_configs:
      - targets: ['kshitijk20-nss.hf.space']
        labels:
          app: 'phishing-detection-api'
    
    # For HuggingFace Space (after deployment)
    # - job_name: 'fastapi-app-hf'
    #   scheme: https
    #   static_configs:
    #     - targets: ['kshitijk20-nss.hf.space']
    #       labels:
    #         app: 'phishing-detection-api'
